services:
  - type: web
    name: ekdant-mitra-mandal
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    region: singapore
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: MANDAL_UPI_ID
        value: ganjaleshivam720-1@oksbi
      - key: MANDAL_PAYEE_NAME
        value: Ekdant Mitra Mandal
      - key: UPLOAD_DIR
        value: /app/server/uploads

